version: "3.7"

services: 
    subsistema1:
        image: gab94es/prueba1:v1
        ports: 
            - 8081:8080
        networks: 
            - cliente-vehiculo
            - cliente-notificacion
            - cliente-factura

    subsistema2:
        image: gab94es/prueba2:v1
        ports:
            - 8082:8080
        networks: 
            - cliente-vehiculo
            - vehiculo-trabajo

    subsistema3spring:
        image: albertozuga/aos-ss3:1.0.2
        ports:
            - 8083:8080
        networks:
            - spring-mysql3
            - vehiculo-trabajo
            - notificacion-trabajo
            - factura-trabajo
            - recambio-trabajo
        depends_on:
            subsistema3mysqldb:
                condition: service_started  
    subsistema3mysqldb:
        image: mysql:8
        restart: always
        networks:
            - spring-mysql3
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=jobs
            - MYSQL_USER=jobservice
            - MYSQL_PASSWORD=jobservice
        volumes:
            - db_data3:/var/lib/mysql

    subsistema4spring:
        image: jvidalc/aos_subsistema4_notificaciones
        ports:
            - 8084:8080
        networks:
            - spring-mysql4
            - cliente-notificacion
            - notificacion-trabajo
        depends_on:
            - subsistema4mysqldb
    
    subsistema4mysqldb:
        image: mysql:8
        restart: always
        networks:
            - spring-mysql4
        environment:
            - MYSQL_ROOT_PASSWORD=qwerty
            - MYSQL_DATABASE=aos4
            - MYSQL_USER=qwerty
            - MYSQL_PASSWORD=qwerty
        volumes:
            - db_data4:/var/lib/mysql
            - ./dump:/docker-entrypoint-initdb.d        

    subsistema5:
        image: rugana90/aos-ss5:0.5
        ports: 
            - 8085:8080
        networks: 
            - cliente-factura
            - factura-trabajo

    subsistema6:
        image: clatange/aos:latest
        ports:
            - 8086:8080
        networks:
            - recambio-trabajo    
        
networks:
    spring-mysql3:
    spring-mysql4:
    recambio-trabajo:
    factura-trabajo:
    cliente-vehiculo:
    cliente-notificacion:
    cliente-factura:
    vehiculo-trabajo:
    notificacion-trabajo:
        
        
volumes:
    db_data3:
    db_data4: